# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-UTC-Now
version:      0.001
version_from: lib/Time/UTC/Now.pm
installdirs:  site
requires:
    Math::BigRat:                  0.02
    Module::Runtime:               0.001
    Time::Unix:                    1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
